version: "3.8"
services:
  # this makes build of my project to use it as a container 
  # that will connect to others
  app:
    build: .
    environment:
      EXCHANGE_API_KEY: "iuV7BDfh875xTAYCoxSc0j9XdIYN2NGJ"
      MONGO_URL: mongodb://mongodb:27017/Users
      POSTGRES_DB: Users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Danicano3264-
    depends_on:
      - postgres
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon --legacy-watch index.js

  mongodb:
    image: mongo
    volumes:
      - ./storeData/mongoData:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Danicano3264-
    ports:
      - "5432:5432"
    volumes:
      - ./storeData/postgresData:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test123
    ports:
      - "5050:80"
    depends_on:
      - postgres
